name: Compiling PAML

on:
  # Trigger action manually
  workflow_dispatch:
  # This is a reusable action that will be called by other actions
  workflow_call:
  pull_request:
  schedule:
    - cron: '30 15 * * 1'
      timezone: "Europe/London"
    
jobs:
  build:
    strategy:
      # All matrix combinations are tested even if one fails
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-latest, macos-15-intel]
        compiler: [gcc, clang]
        # MacOS needs the compiler version, does not work with just 'latest'
        # Windows will have its own environment and compiler, should be
        # added separately
        include:
            - { os: macos-latest,   compiler: gcc-15 }
            - { os: macos-15-intel, compiler: gcc-15 }
            - { os: windows-latest }
            - { os: windows-11-arm }
        exclude:
            - { os: macos-latest,   compiler: gcc }
            - { os: macos-15-intel, compiler: gcc }
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        # Clone the repo so that the rest of actions can run
        uses: actions/checkout@v7
      - name: Set up MSVC environment for Windows compilation
        if: startsWith(matrix.os, 'windows')
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.os == 'windows-11-arm' && 'arm64' || 'amd64' }}
      - name: Compile PAML on Windows
        id: cc-win
        if: ${{ startsWith(matrix.os, 'windows') }}
        shell: cmd
        run: |
          cd src
          nmake -f Makefile.VC
          # Create bin directory and moved binaries there
          if not exist ..\bin mkdir ..\bin
          move *.exe ..\bin
      - name: Compile PAML on Linux
        id: cc-lin
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        shell: bash
        run: |
          cd src
          if [[ "${{ matrix.compiler }}" =~ "clang" ]]; then
            if command -v clang >/dev/null 2>&1; then
              echo "'clang' is already available!"
            else
              echo "'clang' not found, installing... ..."
              sudo apt-get update && sudo apt-get install -y clang
            fi
          fi
          echo Compiling with ${{ matrix.compiler }}
          make -f Makefile CC=${{ matrix.compiler }}
          if ls *.o >/dev/null 2>&1; then
            echo 'Compilation finished, removing output files'
            rm -f *.o
          fi
          # Create bin directory and moved binaries there
          mkdir ../bin
          mv baseml basemlg chi2 codeml ds evolver infinitesites mcmctree pamp yn00 ../bin
      - name: Compile PAML on Unix
        id: cc-unix
        if: ${{ startsWith(matrix.os, 'macos') }}
        shell: bash
        run: |
          cd src
          echo Compiling with ${{ matrix.compiler }}
          # Issue: macOS + gcc-15 has compilation issues with MCMCtree
          if [[ "${{ matrix.os }}" =~ "macos-latest" && "${{ matrix.compiler }}" =~ "gcc-15" ]]; then
            make -f Makefile CC=${{ matrix.compiler }} CFLAGS="-O1 -Wall -Wno-unused-variable -Wno-unused-result"
          else
            make -f Makefile CC=${{ matrix.compiler }}
          fi
          if ls *.o >/dev/null 2>&1; then
            echo 'Compilation finished, removing output files'
            rm -f *.o
          fi
          # Create bin directory and moved binaries there
          mkdir ../bin
          mv baseml basemlg chi2 codeml ds evolver infinitesites mcmctree pamp yn00 ../bin
      - name: Upload Windows PAML binaries
        if: ${{ startsWith(matrix.os, 'windows') }}
        uses: actions/upload-artifact@v7
        with:
          name: paml-binaries-${{ matrix.os }}-cl
          path: bin
      - name: Upload Linux PAML binaries
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        uses: actions/upload-artifact@v7
        with:
          name: paml-binaries-${{ matrix.os }}-${{ matrix.compiler }}
          path: bin
      - name: Upload MacOS PAML binaries
        if: ${{ startsWith(matrix.os, 'macos') }}
        uses: actions/upload-artifact@v7
        with:
          name: paml-binaries-${{ matrix.os }}-${{ matrix.compiler }}
          path: bin